name: Github Pages

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  app:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 11
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@10.2
      with:
        cli: 1.11.1
    - run: mkdir gh-pages
    - run: clojure -M:app > target/index.html
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/
        force_orphan: true
